### ISSUE TITLE
when setDomStorageEnabled(true)，app crash

### ISSUE THREAD

**Issue by gitcfly** [wuruxu/crwebview#3]
当把进行这个设置后setDomStorageEnabled(true)，如果网站页面使用了getItem存储的api,那么app就会崩溃

english：
When setDomStorageEnabled(true) is set, the app will crash if the website page uses the api stored by getItem

W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/chromium/media/R$raw;
W/System.err:     at org.chromium.media.MediaServerCrashListener.startListening(MediaServerCrashListener.java:61)
W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err:     at android.os.Looper.loop(Looper.java:193)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8060)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.chromium.media.R$raw" on path: DexPathList[[dex file "/data/data/com.ckj.demox/code_cache/.overlay/base.apk/classes4.dex", zip file "/data/app/~~yIusEbnAt3voV0vXB-Yc1A==/com.ckj.demox-b13EYhtJ3kxq7JS5hosm-w==/base.apk"],nativeLibraryDirectories=[/data/app/~~yIusEbnAt3voV0vXB-Yc1A==/com.ckj.demox-b13EYhtJ3kxq7JS5hosm-w==/lib/arm64, /data/app/~~yIusEbnAt3voV0vXB-Yc1A==/com.ckj.demox-b13EYhtJ3kxq7JS5hosm-w==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err: 	... 8 more
A/chromium: [FATAL:jni_android.cc(306)] Please include Java exception stack in crash report
A/libc: Fatal signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x7a8b254974 in tid 20252 (com.ckj.demox), pid 20252 (com.ckj.demox)

**Comment by wuruxu** [comment]
这个storage api ，目前没有实现好
